from django.urls import path
from . import views

urlpatterns = [
    path('' , views.index, name='admin_home'),
    path('orders/' ,views.OrdersListView.as_view() ,name='admin_order_list'),
    path('orders/delete/<int:pk>' ,views.OrderDelete ,name='admin_order_delete'),
    path('orders/action/' ,views.OrderSelectedAction ,name='admin_order_action'),
    path('orders/<int:pk>' ,views.OrderDetailView.as_view() ,name='admin_order_detail'),
    path('products/' ,views.ProductListView.as_view() ,name='admin_product_list'),
    path('products/action/', views.ProductSelectedAction, name='admin_product_action'),
    path('products/delete/<int:pk>' ,views.ProductDelete ,name='admin_product_delete'),
    path('products/add/' ,views.ProductAdd.as_view() ,name='admin_product_add'),
    path('products/<int:pk>/edit/', views.ProductEdit.as_view() ,name='admin_product_edit'),
    path('main-categories/' ,views.MainCategories.as_view() ,name='admin_maincategory_list'),
    path('main-categories/add/', views.MainCategoryAdd.as_view(), name='admin_maincategory_add'),
    path('main-categories/<int:pk>/edit/' ,views.MainCategoryEdit.as_view(),name='admin_maincategory_edit'),
    path('sub-categories/' ,views.SubCategories.as_view() ,name='admin_subcategory_list'),
    path('sub-categories/add/', views.SubCategoryAdd.as_view(), name='admin_subcategory_add'),
    path('sub-categories/<int:pk>/edit/', views.SubCategoryEdit.as_view(), name='admin_subcategory_edit'),
    path('sub-categories/<int:pk>/delete/', views.SubCategoryDelete, name='admin_subcategory_delete'),
    path('packs/' ,views.PackList.as_view() ,name='admin_pack_list'),
    path('packs/add' ,views.PackAdd.as_view() ,name='admin_pack_add'),
    path('pack/<int:pk>/delete' ,views.PackDelete ,name='admin_pack_delete'),
    path('pack/<int:pk>/edit/' ,views.PackEdit.as_view() ,name='admin_pack_edit'),
    path('brands/' ,views.BrandsList.as_view() ,name='admin_brand_list'),
    path('brands/add' ,views.BrandAdd.as_view(),name='admin_brand_add'),
    path('brands/<int:pk>/edit' ,views.BrandEdit.as_view() ,name='admin_brand_edit'),
    path('brands/<int:pk>/delete/' ,views.BrandDelete ,name='admin_brand_delete'),
]