# Generated by Django 5.2.14 on 2026-06-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0002_alter_ticket_id_alter_ticketreason_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tickets', verbose_name='عکس از مشکل'),
        ),
    ]
