# Generated by Django 5.2.14 on 2026-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0003_alter_ticket_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportWays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('icon', models.CharField(verbose_name='آیکون')),
                ('opt1', models.CharField(blank=True, null=True, verbose_name='گزینه 1')),
                ('opt2', models.CharField(blank=True, null=True, verbose_name='گزینه 1')),
                ('opt3', models.CharField(blank=True, null=True, verbose_name='گزینه 1')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی',
            },
        ),
    ]
