# Generated by Django 5.2.14 on 2026-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0004_supportways'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportways',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='support_banners', verbose_name='بنر'),
        ),
    ]
