# Generated by Django 5.2.14 on 2026-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0005_supportways_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportways',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
