# Generated by Django 5.2.14 on 2026-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0006_supportways_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(max_length=2000, verbose_name='پاسخ به سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
