# Generated by Django 5.2.14 on 2026-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0007_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuistionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='دسته بندی سوالات')),
            ],
            options={
                'verbose_name': 'دسته بندی سوال',
                'verbose_name_plural': 'دسته بندی سوالات',
            },
        ),
    ]
