# Generated by Django 5.2.14 on 2026-06-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0008_quistioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support_module.quistioncategory', verbose_name='در دسته'),
            preserve_default=False,
        ),
    ]
