# Generated by Django 5.2.14 on 2026-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0009_questions_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuistionCategory',
            new_name='QuestionCategory',
        ),
    ]
