# Generated by Django 5.2.14 on 2026-06-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0010_rename_quistioncategory_questioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='support_module.questioncategory', verbose_name='در دسته'),
        ),
    ]
