# Generated by Django 5.2.14 on 2026-06-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0011_alter_questions_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'دسته بندی سوال', 'verbose_name_plural': 'سوالات متداول'},
        ),
    ]
