# Generated by Django 5.2.14 on 2026-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0012_alter_questioncategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='بسته شده؟'),
        ),
    ]
