# Generated by Django 5.2.14 on 2026-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_module', '0013_remove_ticket_is_active_ticket_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportways',
            name='icon',
            field=models.CharField(max_length=1000, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='supportways',
            name='opt1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='گزینه 1'),
        ),
        migrations.AlterField(
            model_name='supportways',
            name='opt2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='گزینه 1'),
        ),
        migrations.AlterField(
            model_name='supportways',
            name='opt3',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='گزینه 1'),
        ),
    ]
