# Generated by Django 5.2.14 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0023_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن دریافت کننده'),
        ),
        migrations.AddField(
            model_name='order',
            name='plate',
            field=models.CharField(blank=True, null=True, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='آدرس'),
        ),
    ]
