# Generated by Django 5.2.14 on 2026-07-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0031_order_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='merchant_id',
            field=models.CharField(blank=True, null=True, verbose_name='مرچنت آیدی'),
        ),
    ]
