# Generated by Django 5.2.14 on 2026-07-20 16:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0009_carousel_emoji_carousel_icon_carousel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='pallet',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=25, samples=None, verbose_name='رنگ قالب'),
        ),
    ]
