# Generated by Django 5.2.14 on 2026-07-20 16:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0010_carousel_pallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='pallet',
            new_name='color_bg',
        ),
        migrations.AddField(
            model_name='carousel',
            name='color_fore',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=25, samples=None, verbose_name='رنگ متن'),
        ),
    ]
