# Generated by Django 5.2.14 on 2026-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0011_rename_pallet_carousel_color_bg_carousel_color_fore'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='switch_on_break',
            field=models.BooleanField(db_index=True, default=False, verbose_name='سوییچ به رنگ قالب در موبایل'),
        ),
    ]
