# Generated by Django 5.2.14 on 2026-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0012_carousel_switch_on_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='color_bg',
            field=models.CharField(blank=True, default='#fff', max_length=100, null=True, verbose_name='رنگ قالب'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='color_fore',
            field=models.CharField(blank=True, default='#fff', max_length=100, null=True, verbose_name='رنگ متن'),
        ),
    ]
