# Generated by Django 5.2.14 on 2026-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0020_landingpage_delete_sliderslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='کلمه')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
            ],
            options={
                'verbose_name': 'کلمه پرطرفدار',
                'verbose_name_plural': 'کلمات پرطرفدار',
            },
        ),
    ]
