# Generated by Django 5.2.14 on 2026-09-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0021_trendingwords'),
        ('product_module', '0062_remove_product_product_listing_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingwords',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='مرتبط با شاخه اصلی?'),
        ),
        migrations.AddField(
            model_name='trendingwords',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productsubcategory', verbose_name='مرتبط با زیرشاخه?'),
        ),
    ]
