# Generated by Django 5.2.14 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0022_trendingwords_category_trendingwords_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingwords',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),
    ]
