# Generated by Django 5.2.14 on 2026-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_alter_article_created_at_alter_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='متا دسکریپشن'),
        ),
    ]
